-- v1 schema: users, sessions, bookings.
-- No ledger, no idempotency keys, no auth columns. Those arrive in later
-- migrations, which is the point — you'll practise evolving a schema
-- rather than editing history.

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      TEXT        NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE class_sessions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT        NOT NULL,
    starts_at    TIMESTAMPTZ NOT NULL,
    capacity     INT         NOT NULL CHECK (capacity > 0),
    credit_cost  BIGINT      NOT NULL CHECK (credit_cost > 0),
    cancelled_at TIMESTAMPTZ
);

CREATE INDEX idx_class_sessions_starts_at ON class_sessions (starts_at);

CREATE TABLE bookings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL REFERENCES users (id),
    class_session_id BIGINT      NOT NULL REFERENCES class_sessions (id),
    status           TEXT        NOT NULL
                     CHECK (status IN ('CONFIRMED', 'WAITLISTED', 'CANCELLED',
                                       'CONSUMED', 'EXPIRED')),
    position         INT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    cancelled_at     TIMESTAMPTZ
);

-- One live booking per user per session. Partial, so a user can rebook
-- after cancelling. This constraint will refuse a double-booking even when
-- your application code is wrong, which is exactly why it's here and not
-- only in the service layer.
CREATE UNIQUE INDEX idx_bookings_one_live_per_user
    ON bookings (user_id, class_session_id)
    WHERE status <> 'CANCELLED';

CREATE INDEX idx_bookings_session_status ON bookings (class_session_id, status);

-- Seed data so you have something to book on day one.
INSERT INTO users (email) VALUES
    ('alice@example.com'),
    ('bob@example.com');

INSERT INTO class_sessions (name, starts_at, capacity, credit_cost) VALUES
    ('Spin',  now() + interval '2 days', 10, 1),
    ('Yoga',  now() + interval '3 days', 20, 1),
    ('HIIT',  now() + interval '4 days',  8, 2);
