CREATE TABLE users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE
);

CREATE TABLE class_sessions (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT        NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    capacity  INT         NOT NULL CHECK (capacity > 0)
);

CREATE TABLE bookings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users (id),
    class_session_id BIGINT NOT NULL REFERENCES class_sessions (id),
    status           TEXT   NOT NULL CHECK (status IN ('CONFIRMED', 'CANCELLED'))
);

-- A user can only have one confirmed booking per class.
-- They can still book again after cancelling.
CREATE UNIQUE INDEX one_confirmed_booking_per_user
    ON bookings (user_id, class_session_id)
    WHERE status = 'CONFIRMED';

CREATE INDEX bookings_by_class ON bookings (class_session_id, status);

-- Demo data
INSERT INTO users (email) VALUES
    ('alice@example.com'),
    ('bob@example.com'),
    ('carol@example.com');

INSERT INTO class_sessions (name, starts_at, capacity) VALUES
    ('Spin', now() + interval '2 days', 10),
    ('Yoga', now() + interval '3 days', 20),
    ('HIIT', now() + interval '4 days', 2);
