-- Product stage V2: credit accounts and an append only, double entry ledger.
-- Flyway numbers migrations separately, so this file is migration 3.
--
-- Every movement of credits is one credit_transactions row whose
-- ledger_entries sum to zero. For example, booking a 2 credit class moves 2
-- from the member's account to the RESERVED account. credit_accounts.balance
-- is a running total of an account's entries, kept in the same transaction.

CREATE TABLE credit_accounts (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE REFERENCES users (id),
    kind    TEXT   NOT NULL CHECK (kind IN ('MEMBER', 'RESERVED', 'ISSUED')),
    balance BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT credit_accounts_member_has_user
        CHECK ((kind = 'MEMBER') = (user_id IS NOT NULL)),
    -- ISSUED is the source of every credit ever granted, so it is the only
    -- account allowed to go below zero.
    CONSTRAINT credit_accounts_balance_not_negative
        CHECK (kind = 'ISSUED' OR balance >= 0)
);

-- Exactly one RESERVED and one ISSUED account.
CREATE UNIQUE INDEX idx_credit_accounts_one_system_account
    ON credit_accounts (kind) WHERE kind <> 'MEMBER';

CREATE TABLE credit_transactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       TEXT        NOT NULL
               CHECK (kind IN ('GRANT', 'TOP_UP', 'RESERVATION', 'REFUND')),
    booking_id BIGINT      REFERENCES bookings (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT credit_transactions_booking_link
        CHECK ((kind IN ('RESERVATION', 'REFUND')) = (booking_id IS NOT NULL))
);

-- At most one reservation and one refund per booking.
CREATE UNIQUE INDEX idx_credit_transactions_one_per_booking
    ON credit_transactions (booking_id, kind) WHERE booking_id IS NOT NULL;

CREATE TABLE ledger_entries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT      NOT NULL REFERENCES credit_transactions (id),
    account_id     BIGINT      NOT NULL REFERENCES credit_accounts (id),
    amount         BIGINT      NOT NULL CHECK (amount <> 0),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_ledger_entries_account ON ledger_entries (account_id, id);
CREATE INDEX idx_ledger_entries_transaction ON ledger_entries (transaction_id);

-- History is never edited. A correction would be a new, compensating
-- transaction. These triggers apply to every role, including the owner.
CREATE FUNCTION reject_ledger_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Ledger history in % cannot be updated or deleted', TG_TABLE_NAME;
END;
$$;

CREATE TRIGGER ledger_entries_append_only
    BEFORE UPDATE OR DELETE ON ledger_entries
    FOR EACH ROW EXECUTE FUNCTION reject_ledger_change();

CREATE TRIGGER credit_transactions_append_only
    BEFORE UPDATE OR DELETE ON credit_transactions
    FOR EACH ROW EXECUTE FUNCTION reject_ledger_change();

-- Deferred to COMMIT, when all of a transaction's entries exist. An insert of
-- only one side of a transaction therefore fails the whole database transaction.
CREATE FUNCTION check_ledger_transaction_balances() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (SELECT sum(amount) FROM ledger_entries WHERE transaction_id = NEW.transaction_id) <> 0 THEN
        RAISE EXCEPTION 'Ledger transaction % does not balance', NEW.transaction_id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER ledger_entries_balanced
    AFTER INSERT ON ledger_entries
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION check_ledger_transaction_balances();

-- System accounts, one account per existing member and a starting grant of
-- 5 credits each, recorded as real ledger transactions.
INSERT INTO credit_accounts (kind) VALUES ('ISSUED'), ('RESERVED');
INSERT INTO credit_accounts (user_id, kind) SELECT id, 'MEMBER' FROM users ORDER BY id;

DO $$
DECLARE
    issued   BIGINT := (SELECT id FROM credit_accounts WHERE kind = 'ISSUED');
    member   RECORD;
    grant_id BIGINT;
BEGIN
    FOR member IN SELECT id FROM credit_accounts WHERE kind = 'MEMBER' ORDER BY id LOOP
        INSERT INTO credit_transactions (kind) VALUES ('GRANT') RETURNING id INTO grant_id;
        INSERT INTO ledger_entries (transaction_id, account_id, amount)
        VALUES (grant_id, issued, -5), (grant_id, member.id, 5);
        UPDATE credit_accounts SET balance = balance - 5 WHERE id = issued;
        UPDATE credit_accounts SET balance = balance + 5 WHERE id = member.id;
    END LOOP;
END;
$$;
